### ISSUE TITLE
False-Positive Error? 

### ISSUE THREAD

**Issue by fera2k** [DMTF/Redfish-Tools#119]
Hi there,

I'm working on a Proof of Concept solution which is using Swordfish + Redfish CSDL files to simulate some SNIA Swordfish scenarios. This PoC is based on Olingo Library. 

We're trying to use some DMTF Redfish tools validate our PoC. 
One of them is OData CSDL Validator. When we input our $metadata response, we're getting this error:

`Reference: http://docs.oasis-open.org/odata/odata/v4.0/errata03/csd01/complete/vocabularies/Org.OData.Core.V1.xml->Namespace Org.OData.Core.V1 has already been included
`

We have this name in the reference and then in the schema. But I think this error is a false positive. 
I ran it thorugh OData Validation Tool  (https://github.com/OData/ValidationTool/) and I didn´t get this issue.

I've posted the metadata XML here:
https://gist.github.com/fera2k/c3a6b30cf6917bd73f9452f53aa0abf8

**Comment by mraineri** [comment]
The problem is at line 29692, your file is defining the namespace "Org.OData.Core.V1", but top of the file is already including the namespace "Org.OData.Core.V1" as an external reference. There are a couple of related rules around this in the CSDL spec (found here http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part3-csdl.html)
- In section 3.4.1: "The same namespace MUST NOT be included more than once, even if it is declared in more than one referenced document."
- In section 5.5.1: "All edm:Schema elements MUST have a namespace defined through a Namespace attribute which MUST be unique within the document"

Essentially, the uniqueness aspect is broken by both including it as an external reference and as its own definition in the document itself.

Is seems like you're pulling in the complete definition of all of the externally defined namespaces into your local file. What's the purpose of this?

**Comment by fera2k** [comment]
Thanks for the answer @mraineri 
Our PoC is putting together all the CSDL files and outputting them in a single response on the $metadata. I think we should re-work on the references model. 
And thanks for pointing out the documentation.
