### ISSUE TITLE
Allow insertion of page breaks in HTML output for printing

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#146]
Allow insertion of a page break tag that will render invisible in viewed HTML but would create physical page breaks when printed or converted to PDF.  

I found I could insert this tag into the generated HTML:
~~~
<p style="page-break-before: always">
~~~

But I couldn't include it in the source .MD file without affecting the resulting output.  (or is there a Markdown tag equivalent?).

**Comment by akf** [comment]
This is in the current batch of enhancements. I'm using the HTML tag you found and made up a keyword to put in the supplemental file to request a page break: 
~pagebreak~ 

(Github might turn that into strikethrough -- it's just a single tilde on either side of the word "pagebreak.") 

I considered stripping that out for markdown output, but decided to make the HTML substitution for markdown output as well (since you can include HTML in markdown). 

I think I know what might have gone wrong when you tried including the HTML verbatim in the supplemental document: you need the closing </p> tag. Otherwise, it seems the markdown-to-HTML conversion puts the next chunk of text into the paragraph with the page-break-before tag on it.
