### ISSUE TITLE
Some referenced/#included objects rendering as links/odata.id

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#192]
Storage, Processor schemas have a $ref to include the PCIeInterface object definition from PCIeDevice, but this gets rendered as a link to PCIeDevice schema (and description to match).  

This is a case like Status and others, but one where I think we'd want the full object to be rendered (not just a reference to the object definition).  

We will need to look at this and discuss how to detect and differentiate these conditions (hopefully without too much special casing).

**Comment by akf** [comment]
Here's what the doc generator is currently doing. I've wound up unwinding some nested if/else blocks into a bunch of "ifs" with more conditions on them; I hope this is readable (and still accurate).

**extend_property_info** is a method that looks for $ref or anyOf in the description of a property (**prop_info**), looking up what that refers to, and massaging the result to contain the properties we want to include in the documentation. This may involve following another $ref, or adding one of several kinds of "link to" descriptions. (Or, of course, it may terminate in a simple property definition.) 

Inputs and available data include: 

 * what schema we're currently documenting
 * the property name
 * the property definition: **prop_info**. This includes some synthesized attributes identifying the schema (file) this definition came from, and the property name.

There's also a body of schema data that's been ingested and lightly annotated, for looking up properties by reference. 

### The flow of **extend_property_info**  is: 

Look for a "$ref" attribute. (Either directly, or within an "anyOf" property, a "$ref" that ends with "#/definitions/idRef".) 

If no $ref is found, we're done! Otherwise: 

Find the property definition for that $ref by traversing schemas. This is **ref_info**. Determine the following, all of which are boolean:

- **is_other_schema**: Is this from a different schema than the one we're currently generating docs for? True if the schema **ref_info** is from is neither the same schema **prop_info** is from, nor the unversioned counterpart of that schema.
  
- **is_documented_schema**: is this from a schema we're going to output as a section in the documentation? (There's more that goes into this, but basically we have a list.)

- **is_collection**: is this from a "collection" schema? 

- **is_ref_to_same_schema**: For example, this reference resolved to the "top" object in the schema we're currently documenting, e.g., a $ref to Chassis within the Chassis schema. (Obviously, if we detect this we don't want to expand the result out!)

if **is_collection**: if there is an "anyOf" in **ref_info**, look for the latest $ref in that and resolve it, replace **ref_info** with the result. (This is looking for a list of versioned alternatives and resolving to the result of looking up the latest one.)

If **ref_info** has type "object", proceed to determine whether to add link text, and whether to call **extend_property_info** again (to follow a futher $ref):

If neither **is_other_schema** or **is_ref_to_same_schema** is true, the "Link" descriptions don't come into play. If one of those is true:

- if **is_collection**:   _Use the "Link to Collection of ..." description._

- if not **is_collection** and **is_documented_schema**:  _Use the "Link to a ... resource. See Links section ..." description._

- if not **is_collection** and **is_ref_to_same_schema**: _Use "Link to another ... " description._ (This basically overrides the previous line, and gates the next couple -- we won't add 'See ..." text if this is a reference to the top-level schema we're currently documenting. ) 

_This concludes the generation of "Link to" descriptions. In the following cases we add to this existing description:_

- if not **is_collection** and not **is_ref_to_same_schema** and **is_documented_schema** (or "common objects" collection has not been requested): _Add "See the ... schema for details on this property" to the description._

- if not **is_collection** and not **is_ref_to_same_schema** and not **is_documented_schema** (and "common objects" collection has been requested): _Treat this as a Common Object. This includes saving **ref_info** for output in the Common Properties section and adding "See the ..." text to the description._

There is some additional work here to merge data from **prop_info** and **ref_info** (regardless of whether any of the above applied). 

If  we matched the  **is_other_schema** or **is_ref_to_same_schema** condition above, we have some kind of "Link/See" description and we're done. Otherwise, we apply **extend_property_info** to the merged **prop_info** if there is another $ref to follow.

**Comment by jautor** [comment]
@akf I found the difference here - the `PCIeInterface` object is defined in the un-versioned schema, and has an `anyOf` block around it.  There's no reference to `idRef` there, but the tool is treating it as a link anyway.  Removing the anyOf block makes it render as a common object, which is what we'd expect.

Having that object render in-line instead of creating a common object entry will be a new enhancement.  I'll enter a separate issue to track that.

**Comment by jautor** [comment]
I see another reason why `PCIeInterface` causes issues - there are some versions (fixed by later errata) where the definition has the anyOf block to allow for a null type.  I don't know how the generator handles changes in the type definitions (should use the "latest").  This will probably resolve itself, though, once the traversal utilizes only the latest schema and the release annotations.

**Comment by akf** [comment]
Yes, it should be using the "latest," along with whatever is in the unversioned file. I'm still scratching my head over a couple of things here, but I've just realized there are two things about the PCIeInterface definition in the PCIeDevice schema I hadn't expected, and thus probably didn't account for correctly. None of this actually has a bearing on whether the PCIeInterface would be treated as a common object, rendered inline, or rendered as a reference to the definition in PCIeDevice, though.  

1) The PCIeInterface is defined both in the unversioned schema and the latest schema. What the doc generator does in this case, though, is to ignore what's in the unversioned schema -- which would be correct in this case, as the unversioned schema simply specifies either of the definitions from version 1.3.0 or 1.3.1. 

2) I didn't expect an "any of these versions" definition like that for a non-root object in the unversioned schema. That fact is moot given item 1, but more generally, if the doc generator encountered something like this it would probably treat the multiple versions the same way it would treat distinct objects (that is, an anyOf that specified "Widget 1.2" or "Widget 1.3" would be treated similarly to one that  specified "Widget" or "Thingamajig") -- not that we expect that case anyway. 

I'll have to do a little debugging, because the code leads me to expect that the definition in the unversioned schema would be ignored completely, which doesn't square with the fact that you see different behavior when you edit it!

**Comment by akf** [comment]
Well, that line of thinking is a dead-end for me. I get the same behavior when I remove the "anyOf" block as when I leave it in -- probably some change in the last few weeks affected that. 

The whitelist concept (as you've sketched out in another document) is probably the way to go regardless.

**Comment by akf** [comment]
We decided to address this with a "whitelist" capability, in which the user of the doc generator can specify that a specific object should be expanded in place wherever it appears. This is the configuration (to be put in the config file for document generation) that accomplishes it for this case: 

    "object_reference_disposition": {
        "include": [
            "http://redfish.dmtf.org/schemas/v1/PCIeDevice.json#/definitions/PCIeInterface"
        ]
    }
