### ISSUE TITLE
Unable to retrieve data from redfish.dmtf.org

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Tools#199]
First time using this tool.  Using file in ./sample_inputs.  The resultant index.html is a null body.

```
$ python doc_generator.py --format=html --profile sample_inputs/OCPManagedDevice.v1_0_0.json
  Warning: No supplemental file specified and C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator/usersupplement.md not found. Proceeding. (doc_generator.py:1155)
  Warning: Unable to retrieve data from 'http://redfish.dmtf.org/schemas/v1/Resource.v1_4_4.json': timed out (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_gen_util\doc_gen_util.py:66)
  Warning: Unable to retrieve data from 'http://redfish.dmtf.org/schemas/v1/Resource.v1_6_0.json': timed out (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_gen_util\doc_gen_util.py:66)
  Warning: Can't find schema file for http://redfish.dmtf.org/schemas/v1/Resource.v1_6_0.json#/definitions/Location (doc_generator.py:771)
  Warning: Unable to retrieve data from 'http://redfish.dmtf.org/schemas/v1/Resource.v1_8_0.json': timed out (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_gen_util\doc_gen_util.py:66)
  Warning: Can't find schema file for http://redfish.dmtf.org/schemas/v1/Resource.v1_8_0.json#/definitions/Location (doc_generator.py:771)
index.html written.
```

**Comment by akf** [comment]
I should add an example for profile mode! In addition to --profile, you also need to specify a "supplement" file -- the first message there is the clue; the rest stem from it. 

I also discovered a bug (#200) that you will surely hit when you get past this problem, so you'll want to fetch the latest Redfish-Tools from github. 

Try this: 

python doc_generator.py --format=html --profile sample_inputs/OCPManagedDevice.v1_0_0.json --sup sample_inputs/usersupplement.md

This assumes that you have a "json-schema" subdirectory in the directory where you're running the command (I think you must, or you'd have gotten a different error message); otherwise you need to add the path to that to your command, like: 

python doc_generator.py --format=html --profile sample_inputs/OCPManagedDevice.v1_0_0.json --sup sample_inputs/usersupplement.md /path/to/my/json-schema

The sample usersupplement.md has a lot of stuff in it. The thing the doc generator is complaining about missing is the Schema URI Mapping section. lacking this, it  Profile URI Mapping also comes into play if your profile has references to other profiles (as that sample does). Lacking these mappings, when the doc generator tries to follow a reference, it will wind up trying to retrieve the URL.

**Comment by jcleung5549** [comment]
Getting closer.  An index.html file is generated. Only warning messages- are these OK?

```
$ python doc_generator.py --format=html --profile sample_inputs/OCPManagedDevice.v1_0_0.json --sup sample_inputs/usersupplement.md
  Warning: Unable to open Mockup file "mockups/public-rackmount1/Chassis/1U/index.json" to read: [Errno 2] No such file or directory: 'mockups/public-rackmount1/Chassis/1U/index.json' (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\parse_supplement.py:369)
  Warning: Unable to open Mockup file "mockups/public-rackmount1/AccountService/index.json" to read: [Errno 2] No such file or directory: 'mockups/public-rackmount1/AccountService/index.json' (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\parse_supplement.py:369)
  Warning: URI mapping has a bad local path "../Redfish-Tools/doc-generator/sample_inputs" (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\parse_supplement.py:211)
  Warning: Profile URI Mapping found in supplemental document didn't provide any mappings. Output is likely to be incomplete.

 (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\parse_supplement.py:111)
  Warning: Unable to retrieve data from 'http://redfish.dmtf.org/schemas/swordfish/v1/StorageServiceCollection.json': <urlopen error timed out> (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_gen_util\doc_gen_util.py:66)
  Warning: Unable to find data for http://redfish.dmtf.org/schemas/swordfish/v1/StorageServiceCollection.json#/definitions/StorageServiceCollection (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_formatter\doc_formatter.py:711)
  Warning: Unable to retrieve data from 'http://redfish.dmtf.org/schemas/swordfish/v1/StorageSystemCollection.json': <urlopen error timed out> (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_gen_util\doc_gen_util.py:66)
  Warning: Unable to find data for http://redfish.dmtf.org/schemas/swordfish/v1/StorageSystemCollection.json#/definitions/StorageSystemCollection (C:\Users\jcleung\Documents\github external\master-redfish-tools\Redfish-Tools\doc-generator\doc_formatter\doc_formatter.py:711)
index.html written.
```

**Comment by akf** [comment]
Okay-ish. It depends what you're trying to accomplish! Incidentally, I made these samples while working against the DMTF/Redfish repo, and I usually set that as my working directory and use explicit paths to doc_generator.py and the profile and supplemental files. They're geared more toward exercising a few features than to producing sensible output. 

_Warning: Unable to open Mockup file ..._ 
The sample usersupplement.md calls for some mockups to be slurped up and included in the output, and their presence is validated at the start of the process. Profile mode doesn't even use those, so it's okay. 

_Warning: URI mapping has a bad local path "../Redfish-Tools/doc-generator/sample_inputs"_ 
This would be causing you to miss getting some output if you specified OCPBasicServer.v1_0_0.json on the command line instead of OCPManagedDevice.v1_0_0.json, as the OCPBasicServer.v1_0_0.json profile refers to OCPManagedDevice.v1_0_0.json. The cause is that I run this from a different directory; the path needs to be either absolute or relative to your working directory when you run the doc generator. 

_Warning: Profile URI Mapping found in supplemental document didn't provide any mappings. Output is likely to be incomplete._ 
This is the result of the above problem. 

The rest of the messages are about attempts to retrieve a Swordfish schema file that isn't available locally. If a reference to the schema appears in your output at all, the only effect is that you get a link to that URI instead of (possibly) having its contents documented, or getting a link with the schema name instead of just the URI. Probably fine for the Swordfish schemas. At some point we decided to allow for an operating mode where you'd have some files locally and pull others from the internet, which is why you get that message at all. I don't know why the attempt to retrieve them is failing though. It seems to me that this also happens to @jautor. I get it once in awhile when either my connection or the redfish web site is slow, but you're getting it consistently enough that I think python is unable to retrieve files over the network on your system.

I think you'd typically want to have the schemas you're documenting local, so you should review messages like that with an eye to whether you're missing some files, or missed specifying something in the Schema URI Mapping in the supplement.

**Comment by akf** [comment]
I think we've wrapped this one up -- please re-open if I'm mistaken!
