### ISSUE TITLE
The "Profile Specifies" column is not populated

### ISSUE THREAD

**Issue by jcleung5549** [DMTF/Redfish-Tools#201]
The tables under the "Property Details" section have a column name "Profile Specifies" which are unpopulated.

Expected content:
Existence rqmt: "Mandatory", "Recommended", "Conditional", "Optional"
Writable rqmt: "Mandatory", "Recommended", "Optional"

**Comment by akf** [comment]
I'll need to look into this more. I see a smattering of these populated when I use the OCPBasicServer/OCPManagedDevice example and I'm not sure whether any are being missed. I also am not confident whether we intended to include entries for Property Details that aren't mentioned in the profile -- which is what is happening. 

Are you still working with the profiles in the sample_inputs directory?

**Comment by jcleung5549** [comment]
I am creating a new Profile and seeing what the doc_generator creates for documentation.  I used the sample_inputs for a working baseline command.

[OCPRackManagerController.2019.1.json.txt](https://github.com/DMTF/Redfish-Tools/files/3095437/OCPRackManagerController.2019.1.json.txt)

**Comment by jcleung5549** [comment]
I am also looking at the requirement tables in the OPAF's Technical Reference Specification (Part 5).  It has two types of tables:
1. Resource tables
- An entry for each resource with requirements (exists or not)
2. Resource property tables, with columns for read and write. The read and write columns have entries with the following semantics
- M = mandatory
- C = conditional
- R = recommended
- I = if implemented
- <blank> = no requirement, listed for clarity

Currently, OPAF is creating Profile file from the above tables.  I'd like people to follow the reverse process: write Profile file, then auto-generate the tables.

**Comment by jautor** [comment]
This is a documentation case that we don't cover - and we should.  The "Property Details" tables for enumerations should populate with "Mandatory" if those values are included in an "AllOf" comparison for that property value.  And I don't think we stated what should be listed if those value are (by default) in an "AnyOf" comparison.  Does "If Implemented" or "Recommended" make sense?  Because you need to support at least one of those to meet the profile.

But since more read-only properties I wouldn't expect the profile to list out a subset of enums - I also think that if there's no Values/Comparison for an enum property, the table should include the full set of enums with no requirement (blank).

In "Terse" mode does it make sense to remove the un-listed enumeration values if an AllOf/AnyOf exists for a subset?  That to me seems like it may send the wrong message to a developer.

**Comment by akf** [comment]
I think there may have been some bug fixes that related to this issue but weren't linked to it -- they're not jumping out at me in a review of commits. We decided to address this as follows: 

> This issue applies to Profile mode. This column is actually populated sparsely, but is missing information. The "Property Details" tables for enumerations should populate with "Mandatory" if those values are included in an "AllOf" comparison for that property value.
>  
> Additionally, if there's no Values/Comparison for an enum property, the table should include the full set of enums with no requirement (blank). All valid enums should be listed, even in “terse” mode.

This is what the current code on the master branch does, except that it uses the term "Required" instead of "Mandatory." (I will soon be merging in code that changes that word.)

Note that this still results in a column that looks unpopulated much of the time.

**Comment by mraineri** [comment]
@jautor @akf did the referenced pull request address this issue?

**Comment by akf** [comment]
@mraineri it was intended to!
