### ISSUE TITLE
Add keyword for "title" to use for HTML output

### ISSUE THREAD

**Issue by jautor** [DMTF/Redfish-Tools#211]
The HTML title defaults to "Contents" for the current output.  Add a keyword to the input file to specify a document title that can be used to provide a more meaningful title (which appears in the browser tab text).

**Comment by akf** [comment]
Makes sense! Funny thing about why it's picking up "Contents" -- it's looking for the first heading that starts with a single # after "# Introduction". I thought that would be the first heading in the output document, but it turns out the first heading in recent supplemental documents is input with HTML formatting rather than markdown.
