### ISSUE TITLE
[OpenAPI] PhysicalContext $ref in yaml schema

### ISSUE THREAD

**Issue by lindappwu** [DMTF/Redfish-Tools#218]
The PhysicalContext property looks like having incorrect reference to idRef from yaml schema, e.g. Thermal.v1_5_2.yaml

PhysicalContext:
          $ref: http://redfish.dmtf.org/schemas/v1/odata-v4.yaml#/components/schemas/idRef

Instead, it should reference to PhysicalContext schema.

Thanks,
Linda

**Comment by mraineri** [comment]
I haven't been able to come up with a solution for this yet, but this is due to how external references are handled when converting JSON Schema to OpenAPI. There is a simplification made when an external reference is detected to simply point to idRef as opposed to the same type of "anyOf" statement found in JSON Schema. The reason for this is when you use off the shelf tools to generate documentation, they will attempt to traverse the anyOf statement and fill in every possible combination of definitions, which really isn't useful. Will need to come up with a method of determining if an external reference is actually a link to a resource or if it's a reference to a common definition (like an enum).

**Comment by lindappwu** [comment]
Hi Mike, thanks for your explanation. Probably need to go further check whether the schema it points to is a reference or a common definition?

**Comment by mraineri** [comment]
Yeah, I wanted to avoid making external dependencies like that in order to keep the conversion process entirely self contained, but I think that might be the only robust solution here.
