### ISSUE TITLE
VLAN $ref issue in EthernetInterface.v1_5_0.yaml

### ISSUE THREAD

**Issue by snk20501** [DMTF/Redfish-Tools#233]
Hi,

I'm not sure if I can raise schema issue here, so please let me know if this is not proper to report here.
In EthernetInterface.v1_5_0.yaml, VLAN $ref point to wrong file.

It shall be as following,

`VLAN:
          $ref: http://redfish.dmtf.org/schemas/v1/VLanNetworkInterface.v1_1_3.yaml#/components/schemas/VLAN`

**Comment by mraineri** [comment]
The current output of the conversion appears correct to me. The VLAN object referenced by Ethernet Interface is the unversioned definition. This in turn contains an anyOf statement to point to every version of the VLAN object. This is expected since each schema file can grow independently. For example, if VLAN were to have properties added, Ethernet Interface would pick up those new properties without requiring a version change since. We follow the same methodology in both CSDL and JSON Schema.

**Comment by snk20501** [comment]
Understood. Thanks for clarification. Please close this issue.
