### ISSUE TITLE
Doc generator output doesn't extract sufficient levels in hierarchy

### ISSUE THREAD

**Issue by rahlvers** [DMTF/Redfish-Tools#39]
Expand to include extracting content for more complex / hierarchical schema.  Swordfish can provide examples (class of service hierarchy) and inclusion of complex types that are currently excluded from the doc generator output.

**Comment by rahlvers** [comment]
Swordifsh can provide public json schema and documentation usage to demonstrate issue and desired output.

**Comment by jautor** [comment]
This is actually an issue with the CSDL-to-JSON schema converter.  Schemas exhibiting the behavior such as  IOPerformanceLoSCapabilities 1.0.0 have numerous properties (likely all nested complex types in CSDL) rendered in the un-versioned JSON schema, but not in the "versioned" files, which is what the doc generator is using.  So the doc generator is correct (and is catching a bug in the tool chain!), but the converter is wrong.

**Comment by mraineri** [comment]
Moving back to the Document Generator; the items put in the unversioned JSON files were defined in the unversioned namespace within the CSDL. Swordfish moved these definitions later to versioned namespaces, and the current JSON schemas show that.

As far as the hierarchy is concerned, there is a variable in the document generator (max_drilldown) that is used to tell the tool how deep to go when traversing objects. Unfortunately the tool doesn't currently differentiate between complex types and entities, so when you increase this value, you start to pull more properties in from other schemas than it should. There is a planned enhancement to the tool to detect this so that it doesn't start populating properties of other entities into the documentation when it should really just tell the user to refer to a different section of the document.

**Comment by akf** [comment]
I just noticed this oldie is still here. I think work we did mid-2017 was supposed to address this (the doc generator no longer has a max_drilldown variable, and follows new rules for whether to populate an entity or make a reference). Does the current implementation resolve this?

**Comment by mraineri** [comment]
Closing; this issue should be resolved with latest changes in the doc generator. Please reopen this issue if that is not the case.
